config/routes.rb
Rails.application.routes.draw do
  root :to => 'user_sessions#new'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :user_sessions
  resources :users
  resources :microposts do
      collection do
      get 'post_history'
    end
      resources :comments
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  has_many :micropost_comments
  has_many :microposts,  dependent: :destroy, through: :micropost_comments
  validates :replyment, presence: true, length: { maximum: 140 }
  default_scope -> { order(created_at: :desc) }
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @comments= Comment.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @micropost = Comment.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @Comment = Comment.new(comment_params)

    if @comment.save
      redirect_to @comment
    else
      render 'new'
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    @comment = Comment.find(params[:id])

    if @micropost.update(micropost_params)
      redirect_to @micropost
    else
      render 'edit'
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @comment = micropost.find(params[:id])
    @comment.destroy
    redirect_to microposts_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:replyment, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, only: [:create, :destroy]
  before_action :set_comment, only: [ :destroy, :show]
  before_action :set_micropost, only: [:index, :show, :new, :create, :destroy]

  def index
    @comments = @micropost.comments.all
  end

  def show
  end

  def new
    @user = current_user
    @comment = @micropost.comments.new
  end

  def create
    @user = current_user
    @comment = @micropost.comments.where(user_id: current_user.id).new(comment_params)
      if @micropost.save
        flash[:success] = "リプライしました"
        redirect_to micropost_comments_path
      else
        flash[:alert] = "リプライできませんでした"
        redirect_to new_micropost_comment_path
      end
  end

  def destroy
      if @comment.user_id == current_user.id
        @comment.destroy
        redirect_to micropost_comments_path
      else
        flash[:alert] = "このコメントは削除できません"
        redirect_to micropost_comments_path
      end
  end

  private

    def set_micropost
      @micropost = Micropost.find_by(id: params[:micropost_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:replyment, :user_id)
    end

end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">リプライ</h1><br>

<div class="container">
  <div class="table-responsive">
    <table class="table">
      <tr>
        <td align="right">
          <% if @micropost.user.image? %>
            <%= image_tag @micropost.user.image.thumb.url %>
          <% else %>
            <%= image_tag("/images/icon/no-image.png") %>
          <% end %>
        </td>
        <br>
        <td><p class="text-primary">by : <%= @micropost.user.nickname %></p><br>
          <%= @micropost.text %><br>
        </td>
      </tr>
    </table><br>
    <div class="button_wrapper">
        <%= link_to 'リプライ', new_micropost_comment_path, :class => "btn btn-primary btn-lg" %>
    </div><br>
    <table class="table">
      <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td align="right"> <% if comment.user.image? %>
            <%= image_tag comment.user.image.thumb.url %>
          <% else %>
            <%= image_tag("/images/icon/no-image.png") %>
          <% end %>
        </td>
        <td>
          <p class="text-primary">by: <%= comment.user.nickname %></p>
            <p><%= comment.replyment %></p>
        </td>
            <td><%= link_to '削除', micropost_comment_path(@micropost, comment), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
          </td>
      </tr>
        <% end %>
      </tbody>
    </table><br>
  <%= link_to 'Back',microposts_path, :class => "btn btn-secondary" %>
 </div>
</div>

app/views/comments/new.html.erb
<h1 class="text-center">リプライ</h1><br>
<div class="container">
  <div class="form-group">
  <tr>
    <td>
    <% if @micropost.user.image? %>
        <%= image_tag @micropost.user.image.thumb.url %>
      <% else %>
        <%= image_tag("/images/icon/no-image.png") %>
      <% end %><br>
      <br>
    <h5><span class="p-2 badge badge-primary"><th scope="col">by : <%= @micropost.user.nickname %></th></span></h5>
    <th colspan="3"></th>
    </td>
  </tr>
    <p>
      <%= @micropost.text%>
    </p><br>
      <%= form_for(@comment, :url => micropost_comments_path) do |form| %>
        <div class="field">
          <%= form.text_area :replyment , class: 'form-control', placeholder: "リプライ", autofocus: true  %><br>
        </div>
        <div class="button_wrapper">
          <div class="actions">
            <%= form.submit "リプライ" ,:class => "btn btn-primary btn-lg" %><br>
          </div>
        </div>
        <% end %><br>
        <%= link_to 'Back',micropost_comments_path , :class => "btn btn-secondary"%>
    </div>
</div>

app/views/comments/show.html.erb
<p id="notice" class="text-center"><%= notice %></p>
<h1 class ="text-center">Tetsutter</h1>
<div class="container">
  <div class="button_wrapper">
    <%= link_to 'ツイート', new_micropost_path ,:class => "btn btn-primary btn-lg" %>
  </div><br>
    <div class="table-responsive">
          <table class="table">
            <tbody>
          <% @microposts.each do |micropost| %>
            <tr>
                <td class="col-xs-3"><p class="text-primary">by: <%= micropost.user.nickname %></p><br>
                  <p><%= micropost.text %></p>
                </td>
                <td class="col-xs-3"><%= link_to 'リプライ', micropost_comments_path(micropost) ,:class => "btn btn-primary"%></td>
            </tr>
          <% end %>
          </tbody>
      </table>
    </div>
</div>