config/routes.rb
Rails.application.routes.draw do
  root :to => 'user_sessions#new'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :user_sessions
  resources :users
  resources :microposts do
      collection do
      get 'post_history'
    end
      resources :comments
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :microposts
   # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   #  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
    validates :email, presence: true
    validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
    validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
    validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
    validates :nickname, presence:true, on: :update
    validates :gender, presence:true, on: :update
    enum gender: { 男性: 1, 女性: 2, その他: 3}
    validates :birthday, presence:true, on: :update
    validates :introduction, length: { maximum: 140 }
    mount_uploader :image, ImageUploader
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [ :new, :create]

  #テスト用
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = current_user
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to microposts_path
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:success] = "編集しました"
        redirect_to user_path
      else
          flash[:alert] = "編集できませんでした"
          render :edit
      end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation,:nickname, :gender, :birthday, :introduction, :image)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %><br>
    <%= form.text_field :email %><br>
  </div>

  <div class="field">
     <%= form.label :password %><br>
     <%= form.password_field :password %>
  </div>

  <div class="field">
     <%= form.label :password_confirmation %><br>
     <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class ="text-center">プロフィール編集</h1><br>
<div class="container">
<%= form_for(@user) do |form| %>
  <div class="form-group">
        <div class="field">
          <%= form.label "ニックネーム" %><br>
          <%= form.text_field :nickname , class: 'form-control', placeholder: "ニックネーム"  %><br>
        </div><br>
        <div class="field">
          <%= form.label "プロフィール画像" %><br>
          <%= form.file_field :image %><br>
        </div><br>
        <div class="field">
          <%= form.label "性別" %><br>
          <%= form.select :gender, User.genders.keys, {prompt: '選択してください'}, class: 'form-control btn btn-outline-secondary' %>
        </div><br>
        <div class="field">
          <%= form.label "生年月日" %><br>
          <%= form.date_select :birthday %><br>
        </div><br>
        <div class="field">
          <%= form.label "自己紹介" %><br>
          <%= form.text_area :introduction, class: 'form-control', placeholder: "自己紹介" %><br>
        </div>
        <div class="actions">
          <%= form.submit "更新", :class => "btn btn-primary"%><br>
        </div><br>
        <%= link_to 'Back', @user ,:class => "btn btn-secondary"%>
<% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1 class="text-center">Users</h1>
<div class="container">
<table>
  <thead>
    <tr>
      <th>email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<!-- for confirm users  -->
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/users/new.html.erb
<h1 class="text-center">登録</h1>
<%= form_for(@user) do |form| %>
  <div class="container">
      <form class="form-horizontal" action="/action_page.php">
        <div class="form-group">
                <label for="email">Email:</label>
                  <div class="field">
                    <%= form.text_field :email, class: 'form-control', placeholder: "Email"%>
                  </div><br>
                <label for="password">Password:</label>
                  <div class="field">
                    <%= form.password_field :password , class: 'form-control', placeholder: "パスワード" %>
                  </div><br>
                <label for="password_confirmation">Password確認:</label>
                <div class="field">
                  <%= form.password_field :password_confirmation, class: 'form-control', placeholder: "パスワード確認"%><br>
                </div>
            <div class="button_wrapper">
              <div class="actions">
                <%= form.submit "登録", :class => "btn btn-danger btn-lg"%><br>
              </div>
            </div>
       <% end %><br>
      <%= link_to 'Back', login_path ,:class => "btn btn-secondary" %>
  </div>
</form>

app/views/users/show.html.erb
<h1 class="text-center">プロフィール</h1>
<p id="notice" class="text-center"><%= notice %></p>
<div class="container">
      <div class="row">
        <table class="table table-user-information">
                    <tbody>
                            <tr>
                              <td>
                                <% if @user.image? %>
                                  <%= image_tag @user.image.thumb.url %>
                                <% else %>
                                  <%= image_tag("/images/icon/no-image.png") %>
                                <% end %>
                              </td>
                            </tr>
                            <tr>
                              <td>
                                <strong>ニックネーム:</strong>
                                <%= @user.nickname %>
                              </td>
                            </tr>
                            <tr>
                              <td>
                                <strong>性別:</strong>
                                <%= @user.gender %>
                              </td>
                            </tr>
                            <tr>
                              <td>
                              <strong>生年月日:</strong>
                              <%= @user.birthday %>
                             </td>
                            </tr>
                          <tr>
                            <td>
                            <strong>自己紹介:</strong>
                            <%= @user.introduction %>
                           </td>
                          </tr>
                      </tbody>
        </table>
      </div>
<%= link_to '編集', edit_user_path(@user),:class => "btn btn-success" %>
<%= link_to 'Back', microposts_path,:class => "btn btn-secondary" %>

</div>