config/routes.rb
Rails.application.routes.draw do
  root :to => 'user_sessions#new'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :user_sessions
  resources :users
  resources :microposts do
      collection do
      get 'post_history'
    end
      resources :comments
  end
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user, optional: true
  has_many :micropost_comments
  has_many :comments, dependent: :destroy, through: :micropost_comments
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :text, presence: true, length: { maximum: 140 }
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :require_login
    before_action :set_micropost, only: [:show, :edit, :update, :destroy]
    before_action :indicate_current_user, only: [:new, :edit, :post_history, :update, :destroy]
    before_action :check_correct_user, only: [:edit, :destroy]

    def index
      @microposts = Micropost.all
    end

    def show
    end

    def new
      @micropost = Micropost.new
    end

    def edit
    end

    def post_history
      @microposts = @user.microposts.all
    end

    def create
      @micropost = Micropost.where(user_id: current_user.id).new(micropost_params)
      if @micropost.save
        flash[:success] = "ツイートしました!"
        redirect_to microposts_path
      else
        flash[:alert] = "ツイートできませんでした!"
        redirect_to new_micropost_path
      end
    end

    def update
        if @micropost.update(micropost_params)
          flash[:success] = "更新しました"
          redirect_to microposts_path
        else
          flash[:alert] = "更新できませんでした"
          render :edit
        end
    end

    def destroy
      @micropost.destroy
      flash[:success] = "Micropost destroyed"
      redirect_to post_history_microposts_path
    end

    private

      def check_correct_user
        unless @micropost.user_id == current_user.id
          flash[:alert] = "You do not have permission"
          render :show
        end
      end

      def indicate_current_user
        @user = current_user
      end

      def set_micropost
        @micropost = Micropost.find(params[:id])
      end

      def micropost_params
        params.require(:micropost).permit(:id,:text, :tag, :user_id)
      end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<div class="container">
  <div class="table-responsive">
    <div class="form-group">
      <table>
        <tr>
          <td>
            <% if @user.image? %>
                <%= image_tag @user.image.thumb.url %>
              <% else %>
                <%= image_tag("/images/icon/no-image.png") %>
              <% end %><br>
              <br>
          </td>
          <td>
            <p class="text-primary">by : <%= @user.nickname %></p>
          </td>
          <th colspan="3"></th>
        </tr><br>
      </table><br>
      <%= form_for(@micropost) do |form| %>
              <div class="field">
                  <%= form.text_area :text, class: 'form-control', placeholder: "ツイート", autofocus: true  %><br>
              </div>
              <div class="center-block">
                <div class="actions">
                  <%= form.submit "ツイート",:class => "btn btn-primary btn-lg"%>
                </div>
              </div>
            <% end %><br>
        <%= link_to 'Back', microposts_path ,:class => "btn btn-secondary"%>
      </div>
  </div>
</div>

app/views/microposts/edit.html.erb
<h1 class="text-center">ツイート編集</h1><br>

<%= render 'form' %>

app/views/microposts/index.html.erb
<p id="notice" class="text-center"><%= notice %></p>
<h1 class ="text-center">Tetsutter</h1><br>
<div class="container">
  <div class="button_wrapper">
    <%= link_to 'ツイート', new_micropost_path ,:class => "btn btn-primary btn-lg" %>
  </div><br>
    <div class="table-responsive">
          <table class="table">
            <tbody>
          <% @microposts.each do |micropost| %>
            <tr>
                <td>
                  <% if micropost.user.image? %>
                    <%= image_tag micropost.user.image.thumb.url %>
                  <% else %>
                    <%= image_tag("/images/icon/no-image.png") %>
                  <% end %>
                </td>
                <td class="col-xs-3"><p class="text-primary">by: <%= micropost.user.nickname %></p><br>
                  <p><%= micropost.text %></p><br>
                </td>
                <td class="col-xs-3"><%= link_to 'リプライ', micropost_comments_path(micropost) ,:class => "btn btn-primary"%></td>
            </tr>
          <% end %>
          </tbody>
      </table>
    </div>
</div>

app/views/microposts/mypage.html.erb
<p id="notice" class="text-center"><%= notice %></p>
<h1 class ="text-center">My Post History</h1>
<div class="container">
  <div class="button_wrapper">
    <%= link_to 'New MicroPost', new_micropost_path ,:class => "btn btn-primary btn-lg" %>
  </div>
    <div class="table-responsive">
          <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Nickname</th>
                <th scope="col">Post</th>
                <th colspan="3"></th>
              </tr>
            </thead>
        <tbody>
          <% @microposts.each do |micropost| %>
            <tr>
                <div class="row">
                    <div class="col-sm">
                        <td class="col-xs-3"><%= micropost.user.nickname %></td>
                    </div>
                    <div class="col-sm">
                        <td class="col-xs-3"><%= micropost.text %></td>
                    </div>
                </div>
            </tr>
            <tr>
              <td><%= link_to 'Comment', micropost_comments_path(micropost) ,:class => "btn btn-info"%></td>
              <td><%= link_to 'show', micropost_path(micropost) ,:class => "btn btn-warning"%></td>
              <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } ,:class => "btn btn-danger"%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/microposts/new.html.erb
<h1 class="text-center">新規ツイート</h1><br>

<%= render 'form' %>

app/views/microposts/post_history.html.erb
<p id="notice" class="text-center"><%= notice %></p>
<h1 class ="text-center">履歴</h1><br>
<div class="container">
  <div class="button_wrapper">
    <%= link_to 'ツイート', new_micropost_path ,:class => "btn btn-primary btn-lg" %>
  </div><br>
    <div class="table-responsive">
      <table class="table">
        <tbody>
      <% @microposts.each do |micropost| %>
        <tr>
          <td align="right">
            <% if micropost.user.image? %>
              <%= image_tag micropost.user.image.thumb.url %>
            <% else %>
              <%= image_tag("/images/icon/no-image.png") %>
            <% end %>
          </td>
            <td class="col-xs-3"><p class="text-primary">by: <%= micropost.user.nickname %></p><br>
              <p><%= micropost.text %></p><br>
              <%= link_to '編集', edit_micropost_path(micropost) ,:class => "btn btn-success"%>
              <%= link_to '削除', micropost, method: :delete, data: { confirm: 'Are you sure?' } ,:class => "btn btn-danger"%>
            </td>
            <td>
              <%= link_to 'リプライ', micropost_comments_path(micropost) ,:class => "btn btn-primary"%>

            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/microposts/show.html.erb
<p id="notice" class="text-center"><%= notice %></p>

<div class="container">

  <table class="table">
        <thead>
          <tr class="bg-primary">
              <th scope="col"><p class="text-white">ツイート</p></th>
              <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
            <tr>
              <div class="row">
                  <div class="col-sm">
                      <td class="col-xs-3"><%= @micropost.text %></td>
                  </div>
                  <div class="">
                    <td class="col-xs-3"><%= @micropost.tag %></td>
                  </div>
            </tr>
        </tbody>
  </table>


    <td class="text-center"><%= link_to '編集', edit_micropost_path(@micropost) ,:class => "btn btn-success"%></td>
    <td class="text-center"><%= link_to 'Back', post_history_microposts_path ,:class => "btn btn-secondary"%></td>

  </div>