config/routes.rb
Rails.application.routes.draw do
  root :to => 'user_sessions#new'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :user_sessions
  resources :users
  resources :microposts do
      collection do
      get 'post_history'
    end
      resources :comments
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Micropost</title>
      <%= stylesheet_link_tag    "application" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
      <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>
  <body>
  <div id="nav-drawer" >
      <div class="d-flex flex-column flex-md-row align-items-left p-3 px-md-auto mb-auto bg-white border-bottom shadow-sm">
         <h5 class="my-0 mr-md-auto font-weight-normal">Tetsutter</h5><br>
      <% if current_user %>
      <input id="nav-input" type="checkbox" class="nav-unshown">
      <label id="nav-open" for="nav-input"><span></span></label>
      <label class="nav-unshown" id="nav-close" for="nav-input"></label>
      <div id="nav-content" class="mr-auto"><br>
        <h5>
          <div class="button_wrapper">
            <a href="#"><%= link_to "履歴", post_history_microposts_path , :class =>"text-info"%></a><br>
              <br>
            <a href="#"><%= link_to "プロフィール", user_path(current_user.id), :class =>"text-success" %></a><br>
              <br>
            <a href="#"><%= link_to "ツイート", microposts_path, :class =>"text-primary" %></a><br>
              <br>
            <a href="#"><%= link_to "ログアウト", logout_path, method: :post  , :class => "text-secondary"%></a>
          </div>
        </h5>
       </div>
   </div>
  </div>
      <% else %>
        <nav>
          <a class="text-dark" href="#"><%= link_to "登録", new_user_path , :class => "btn btn-danger"%></a>
        </nav>
      <% end %>

    </div>
  </div>
  <div><br>
    <p id="alert" class="text-center"><%= flash[:alert] %></p>
    <p id="success" class="text-center"><%= flash[:success] %></p>
  </div>
    <%= yield %>
  </body>
</html>